### ISSUE TITLE
llamafile-main not found?

### ISSUE THREAD

**Issue by vinay235** [iverly/llamafile-docker#1]
Running the command: 
`$ winpty docker run -it --rm -v 'C:\Users\Vinay Datta\genai\model\':/model iverly/llamafile-docker:main-latest -m /model
/usr/src/app/llamafile-main: 1: Not: not found
`

**Comment by iverly** [comment]
Hey @vinay235,

I've fixed the issue with [312ccaa](https://github.com/iverly/llamafile-docker/commit/312ccaa94e25aa140eb48dabcb3fa761e8a7fc1a).
