### ISSUE TITLE
Specific Llamafiles rather than -m model

### ISSUE THREAD

**Issue by gad2103** [iverly/llamafile-docker#5]
Thanks for making this. One suggestion is to modify the Dockerfile so that at build time you are passing an argument for a specific llamafile. That way you don't have the extra step of needing to specify the gguf files and mounting them in a volume. Maybe I'm just missing the point, but using the executable with gguf files as an argument feels like it's missing some of the value of llamafile just being a file you run. Would love your thoughts on this.

**Comment by iverly** [comment]
Thank you for the suggestion! To address your use case, if you’d like to specify a model at build time, I recommend creating your own Dockerfile based on mine (FROM iverly/llamafile-docker:latest). You can add the required steps to include the model file by using:

```Dockerfile
COPY /path-to-your-model /container-path-to-model
# or
RUN wget <url-to-model> -O /container-path-to-model
```

Then, modify the command by overriding the CMD line like this:

```Dockerfile
CMD ["--server", "--host", "0.0.0.0", "-m", "/container-path-to-model"]
```

Let me know if you have further questions!

**Comment by gad2103** [comment]
Hey! Thanks for getting back to this comment so quickly. I forked and will do just that.
